import json

# Function to generate quiz questions
def generate_quiz():
    quiz = {
        "title": "General knowledge quiz about C. elegans",
        "source": "Generated by GPT4o",
        "questions": []
    }

    sample_questions = [
        ("What is the common name for Caenorhabditis elegans?", "Nematode", ["Flatworm", "Earthworm", "Leech"]),
        ("How many cells does an adult C. elegans hermaphrodite have?", "959", ["1050", "850", "1024"]),
        ("What is the primary food source for C. elegans in lab conditions?", "E. coli", ["Algae", "Fungi", "Bacteria mix"]),
        ("Who first identified and described C. elegans?", "Maupas", ["Brenner", "Darwin", "Watson"]),
        ("What is the average lifespan of C. elegans in the lab?", "2-3 weeks", ["1 month", "1 year", "5 days"]),
        ("How many neurons does an adult C. elegans have?", "302", ["256", "450", "1000"]),
        ("Which organ in C. elegans serves as its nervous system control center?", "Nerve ring", ["Ganglion", "Brain", "Spinal cord"]),
        ("How does C. elegans reproduce?", "Hermaphroditically", ["Asexually", "Parthenogenetically", "Only sexually"]),
        ("Which famous scientist established C. elegans as a model organism?", "Sydney Brenner", ["Francis Crick", "James Watson", "Barbara McClintock"]),
        ("What is the genome size of C. elegans?", "~100 million base pairs", ["50 million", "200 million", "10 million"]),
        ("How many chromosomes does C. elegans have?", "6", ["8", "10", "12"]),
        ("What is the role of dauer stage in C. elegans?", "Survival under harsh conditions", ["Reproduction", "Molting", "Sensory adaptation"]),
        ("What is a major advantage of C. elegans as a model organism?", "Transparent body", ["Large size", "Complex brain", "Long lifespan"]),
        ("What technique is commonly used to silence genes in C. elegans?", "RNA interference (RNAi)", ["CRISPR", "Gene knockout", "Electroporation"]),
        ("Which Nobel Prize-winning discovery was made in C. elegans research?", "Programmed cell death", ["Antibiotics", "Gene splicing", "Stem cells"]),
        ("Which sensory modality does C. elegans use to detect food?", "Chemotaxis", ["Sonar", "Electrosensing", "Infrared detection"]),
        ("What is the main method of locomotion for C. elegans?", "Sinusoidal movement", ["Jumping", "Rolling", "Crawling"]),
        ("What structure in C. elegans is responsible for touch sensitivity?", "Mechanoreceptors", ["Photoreceptors", "Olfactory neurons", "Thermoreceptors"]),
        ("How do researchers commonly track gene expression in C. elegans?", "Fluorescent markers", ["Radioactive labeling", "MRI scanning", "Electron microscopy"]),
        ("Which neurotransmitter is crucial for movement in C. elegans?", "Acetylcholine", ["Dopamine", "Serotonin", "Glutamate"]),
        ("What is the name of the larval stages in C. elegans development?", "L1-L4", ["A1-A4", "M1-M4", "C1-C4"]),
        ("What is the main mode of reproduction in wild-type C. elegans?", "Self-fertilization", ["External fertilization", "Budding", "Binary fission"]),
        ("What is a common mutant strain of C. elegans used in research?", "unc-54", ["WT-42", "neo-1", "brn-5"]),
        ("Which part of the C. elegans body contains its gonads?", "Midsection", ["Head", "Tail", "Anterior region"]),
        ("How does C. elegans sense temperature?", "Thermotaxis", ["Electroreception", "Sonar", "Infrared sensing"]),
        ("What is the primary function of the excretory system in C. elegans?", "Osmoregulation", ["Digestion", "Circulation", "Reproduction"]),
        ("Which signaling pathway plays a role in C. elegans vulval development?", "EGF signaling", ["Sonic Hedgehog", "Notch", "Wnt"]),
        ("What is the primary function of the cuticle in C. elegans?", "Protection and structure", ["Digest food", "Sense vibrations", "Absorb nutrients"]),
        ("How does C. elegans respond to high oxygen levels?", "Avoidance", ["Attraction", "Neutral response", "Rapid movement"]),
        ("Which gene is associated with lifespan extension in C. elegans?", "daf-2", ["p53", "ras-1", "wnt-4"]),
        ("What is the main organ responsible for digestion in C. elegans?", "Intestine", ["Gizzard", "Crop", "Esophagus"]),
        ("Which signaling pathway is crucial for dauer formation?", "Insulin signaling", ["Wnt signaling", "Notch signaling", "Hedgehog signaling"]),
        ("What is the function of amphid neurons in C. elegans?", "Chemosensation", ["Vision", "Hearing", "Balance"]),
        ("How many larval stages does C. elegans have?", "4", ["3", "5", "6"]),
        ("Which molecule is responsible for aging regulation in C. elegans?", "DAF-16", ["TOR", "P53", "Notch"]),
        ("How many cells does an adult C. elegans hermaphrodite have?", "959", ["1050", "850", "1024"]),
        ("What is the primary food source for C. elegans in lab conditions?", "E. coli", ["Algae", "Fungi", "Bacteria mix"]),
        ("Who first identified and described C. elegans?", "Maupas", ["Brenner", "Darwin", "Watson"]),
        ("What is the average lifespan of C. elegans in the lab?", "2-3 weeks", ["1 month", "1 year", "5 days"]),
        ("How many neurons does an adult C. elegans have?", "302", ["256", "450", "1000"]),
        ("Which organ in C. elegans serves as its nervous system control center?", "Nerve ring", ["Ganglion", "Brain", "Spinal cord"]),
        ("How does C. elegans reproduce?", "Hermaphroditically", ["Asexually", "Parthenogenetically", "Only sexually"]),
        ("Which famous scientist established C. elegans as a model organism?", "Sydney Brenner", ["Francis Crick", "James Watson", "Barbara McClintock"]),
        ("What is the genome size of C. elegans?", "~100 million base pairs", ["50 million", "200 million", "10 million"]),
        ("How many chromosomes does C. elegans have?", "6", ["8", "10", "12"]),
        ("What is the role of dauer stage in C. elegans?", "Survival under harsh conditions", ["Reproduction", "Molting", "Sensory adaptation"]),
        ("What is a major advantage of C. elegans as a model organism?", "Transparent body", ["Large size", "Complex brain", "Long lifespan"]),
        ("What technique is commonly used to silence genes in C. elegans?", "RNA interference (RNAi)", ["CRISPR", "Gene knockout", "Electroporation"]),
        ("Which Nobel Prize-winning discovery was made in C. elegans research?", "Programmed cell death", ["Antibiotics", "Gene splicing", "Stem cells"]),
        ("Which sensory modality does C. elegans use to detect food?", "Chemotaxis", ["Sonar", "Electrosensing", "Infrared detection"]),
        ("What is the main method of locomotion for C. elegans?", "Sinusoidal movement", ["Jumping", "Rolling", "Crawling"]),
        ("What structure in C. elegans is responsible for touch sensitivity?", "Mechanoreceptors", ["Photoreceptors", "Olfactory neurons", "Thermoreceptors"]),
        ("How do researchers commonly track gene expression in C. elegans?", "Fluorescent markers", ["Radioactive labeling", "MRI scanning", "Electron microscopy"]),
        ("Which neurotransmitter is crucial for movement in C. elegans?", "Acetylcholine", ["Dopamine", "Serotonin", "Glutamate"]),
        ("What is the name of the larval stages in C. elegans development?", "L1-L4", ["A1-A4", "M1-M4", "C1-C4"]),
        ("What is the main mode of reproduction in wild-type C. elegans?", "Self-fertilization", ["External fertilization", "Budding", "Binary fission"]),
        ("What is a common mutant strain of C. elegans used in research?", "unc-54", ["WT-42", "neo-1", "brn-5"]),
        ("Which part of the C. elegans body contains its gonads?", "Midsection", ["Head", "Tail", "Anterior region"]),
        ("How does C. elegans sense temperature?", "Thermotaxis", ["Electroreception", "Sonar", "Infrared sensing"]),
        ("What is the primary function of the excretory system in C. elegans?", "Osmoregulation", ["Digestion", "Circulation", "Reproduction"]),
        ("Which signaling pathway plays a role in C. elegans vulval development?", "EGF signaling", ["Sonic Hedgehog", "Notch", "Wnt"]),
        ("What is the primary function of the cuticle in C. elegans?", "Protection and structure", ["Digest food", "Sense vibrations", "Absorb nutrients"]),
        ("How does C. elegans respond to high oxygen levels?", "Avoidance", ["Attraction", "Neutral response", "Rapid movement"]),
        ("Which gene is associated with lifespan extension in C. elegans?", "daf-2", ["p53", "ras-1", "wnt-4"]),
        ("What is the main organ responsible for digestion in C. elegans?", "Intestine", ["Gizzard", "Crop", "Esophagus"])
    ]


    answer_refs = ["A", "B", "C", "D"]
    
    for i in range(50):
        question_data = sample_questions[i]
        question_text = question_data[0]
        correct_answer = question_data[1]
        incorrect_answers = question_data[2]
        
        answers = []
        options = [correct_answer] + incorrect_answers
        for idx, option in enumerate(options):
            answers.append({
                "ref": answer_refs[idx],
                "ans": option,
                "correct": option == correct_answer
            })
        
        quiz["questions"].append({
            "question": question_text,
            "answers": answers
        })

    return quiz

# Generate quiz and save it to a JSON file
quiz_data = generate_quiz()
with open("quiz_questions.json", "w", encoding="utf-8") as f:
    json.dump(quiz_data, f, indent=4)

print("Quiz JSON file has been generated: quiz_questions_general_knowledge.json")
