from openworm_ai.quiz.QuizModel import MultipleChoiceQuiz, Question, Answer
from openworm_ai.quiz.Templates import GENERATE_Q, TEXT_ANSWER_EXAMPLE

from openworm_ai.utils.llms import get_llm_from_argv, ask_question_get_response


def save_quiz(num_questions, num_answers, llm_ver):
    question = (
        GENERATE_Q.replace("<QUESTION_NUMBER>", str(num_questions)).replace(
            "<ANSWER_NUMBER>", str(num_answers)
        )
        + TEXT_ANSWER_EXAMPLE
    )

    response = ask_question_get_response(question, llm_ver)

    quiz = MultipleChoiceQuiz(
        title="General knowledge quiz with %i questions" % num_questions,
        source="Generated by %s" % llm_ver,
    )

    last_question = None
    indexing = ["A", "B", "C", "D"]

    for line in response.split("\n"):
        if "QUESTION" in line:
            question = line.split(":")[-1].strip()
            print("Question: <%s>" % question)
            last_question = Question(question=question)
            quiz.questions.append(last_question)
        elif "CORRECT ANSWER" in line:
            ans = line.split(":")[-1].strip()
            print("CORRECT ANSWER: <%s>" % ans)
            i = len(last_question.answers)
            last_question.answers.append(Answer(indexing[i], ans, True))
        elif "WRONG ANSWER" in line:
            ans = line.split(":")[-1].strip()
            print("WRONG ANSWER: <%s>" % ans)
            i = len(last_question.answers)
            last_question.answers.append(Answer(indexing[i], ans, False))

    print("===============================\n  Generated quiz:\n")
    print(quiz.to_yaml())

    quiz.to_json_file(
        "openworm_ai/quiz/samples/%s_%iquestions.json"
        % (llm_ver.replace(":", "_"), num_questions)
    )


if __name__ == "__main__":
    import sys

    llm_ver = get_llm_from_argv(sys.argv)

    save_quiz(50, 4, llm_ver)
