# This workflow will test all of the Python scripts in this package in the correct sequence

name: Test Python scripts

on:
  push:
    branches: [ main, development, experimental, test* ]
  pull_request:
    branches: [ main, development, experimental, test* ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.9, 3.11, 3.12 ]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python  ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version:  ${{ matrix.python-version }}

    - name: Install package
      run: |
          pip install .[test]

    - name: Install ollama and small LLM
      run: |
          pip install ollama
          ollama pull llama3.2:1b


    - name: Test all
      run: | 
        ./regenerateAndTest.sh -free  # Only test the parts not requiring any API keys...

    - name: Final version info
      run: |
        pip list
        env

